### ISSUE TITLE
Unable to get notification icon

### ISSUE THREAD

**Issue by LakshmiEvana** [EddyVerbruggen/nativescript-local-notifications#23]
``` js
  LocalNotifications.schedule([{
    id: 1,
    title: 'The title',
    body: 'Recurs every minute until cancelled',
    ticker: 'The ticker',
    badge: 1,
    smallIcon: 'res://heart.png',
    interval: 'minute',
    sound: null, // suppress the default sound
    at: new Date(new Date().getTime() + (10 * 1000)) // 10 seconds from now
  }]).then(
      function() {
        console.log("Notification scheduled");
      },
      function(error) {
        console.log("scheduling error: " + error);
      }
  )
```

**Comment by EddyVerbruggen** [comment]
Would you care to elaborate? I'm not a robot (although people tend to think that) so a bit of context would be great. Also information on the platform used and what you've already tried will make this all the more pleasant.

**Comment by sarvagayatri** [comment]
Hi,
Actually we are running app on android, and we are using notifications where we want to keep app icon to the notification. as given in npm we have added .png to appresourses and given small icon property value as
` smallIcon: 'res://heart.png',`
but its either showing up the icon on notifcation or giving any error

**Comment by mn-martin** [comment]
The implementation is fine and should not be changed since it better fits the existing {NS} API. This is just a documentation flaw.

1. don't use `'res://heart.png'`, remove the file extension (`'res://heart'`)
2. using the same icon for small & large doesn't seem to work (probably it has something to do with 3.)
3. [there are some things to consider with notification icons on android](https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html)

**Comment by EddyVerbruggen** [comment]
Thanks for the documentation gotcha! It was indeed incorrect.
