### ISSUE TITLE
After Reboot my device, i got the issue as  (no valid small icon)

### ISSUE THREAD

**Issue by umasankarTS** [EddyVerbruggen/nativescript-local-notifications#51]
![notification issue](https://cloud.githubusercontent.com/assets/28996593/26677496/e29ed832-46e9-11e7-8f67-e5329ed2736f.png)
Hello Team,
When I reboot my device,  I got the issue as no valid small icon found, and app Unfortunately stopped.
Please Help..!

**Comment by yyankov** [comment]
Happens every time a notification should be showed up after device reboot.
Can this be reviewed with priority as it is a blocker issue and makes the plugin unusable?

**Comment by EddyVerbruggen** [comment]
Well, the "team" (me) is on a little Christmas break 😄 

That being said, I think I know what the problem is. Can you try passing an `icon` parameter with the notification? I know it's not in the TypeScript definition so you may get a warning, so you'll probably have to add it like `options["icon"] = `. If that icon is valid, reboot the device and see if the same error still pops up. If it's gone then I know what to change.

**Comment by yyankov** [comment]
Hi Eddy,

Thank you for the quick response! 
I tried adding options["icon"] = 'res://icon' (using the app icon) and scheduling a new notification but unfortunately after a reboot the app still crashes.

**Comment by EddyVerbruggen** [comment]
Did you get exact same error as the one in the screenshot above? If not please do ‘adb logcat’ to find the stacktrace :)

**Comment by yyankov** [comment]
I managed to prevent the crash by changing "icon" to "smallIcon" here:
https://github.com/EddyVerbruggen/nativescript-local-notifications/blob/master/native-src/android/src/com/telerik/localnotifications/NotificationRestoreReceiver.java#L50

However I can see that regular notifcations have a larger icon on the right but a notification that appears after a reboot only has the tiny icon at the top left and no icon on the right side.

**Comment by EddyVerbruggen** [comment]
Thanks for helping me figure this one out. I've fixed the crash in version 2.0.2.
