### ISSUE TITLE
No sound, no notification, only listed in notifications

### ISSUE THREAD

**Issue by michaelhornak** [EddyVerbruggen/nativescript-local-notifications#61]
Hi, I was trying to implement your plugin to my android nativescript app but notification message or sound didnt show up after calling notification. Notification was only listed in other notifications list and app icon was showing red dot. I thought the problem was in my app, but after downloading your demo app repository, the issues were same on every type of notification in demo app. No message showing, no sound played, only displayed in notification list.  I tried also older versions of plugin in your demo app, there the default sound notification started to work, but still no message showing in the top of the screen.  I am testing it on Android 6.0.1 phone. Do you have any clue what could be the problem?

**Comment by michaelhornak** [comment]
@EddyVerbruggen could you please verify if https://github.com/EddyVerbruggen/nativescript-local-notifications-demo is working for you?

**Comment by yyankov** [comment]
Same here - testing with Android 7.0.

**Comment by EddyVerbruggen** [comment]
There seem to have been a few changes in Android 7 (and again in Android 8). I've been testing and fixing some things for those Android versions today, and those changes will be part of plugin version 2.0.0.

Note that Android 7 may not show the notification popup, but it does play a sound. Android 8 does show a popup because it uses a new way to schedule notifications. Not sure if Android 7 can be persuaded to behave differently, but I'm open to ideas, of course.
