### ISSUE TITLE
Every 30 minutes notification

### ISSUE THREAD

**Issue by egvrcn** [EddyVerbruggen/nativescript-local-notifications#91]
Is there a way to do notification every 30 minutes instead of every minute?

**Comment by EddyVerbruggen** [comment]
Adding this feature on Android is super easy because the repeat interval takes an arbitrary number of milliseconds. On iOS though, it's a fixed value ("minute", etc).

That's why I haven't added it to the plugin interface and the best way to do this is probably schedule 2 similar notifications: one that triggers now and repeats every hour, and one that triggers in 30 minutes and repeats every hour as well.
